/*
 * File: app/model/Place.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.Place', {
    extend: 'Ext.data.Model',

    config: {
        fields: [
            {
                name: 'id',
                type: 'int'
            },
            {
                name: 'name'
            },
            {
                name: 'location'
            },
            {
                name: 'lat',
                type: 'float'
            },
            {
                name: 'lng',
                type: 'float'
            }
        ],
        proxy: {
            type: 'rest',
            url: 'http://localhost:55434/api/place'
        },
        validations: [
            {
                type: 'presence',
                field: 'name'
            }
        ]
    }
});